### PR TITLE
fix(bridge): bridge status based on whether port listens or not

### PR DESCRIPTION
**Pull request by grdddj**
Addressing issue #86
- changing bridge status retrieving logic to just look whether the port is listening

### CODE REVIEW

**Review by tsusanka — APPROVED** [review]

**Comment by tsusanka** [comment]
That's very curious that it does take 2s for Bridge to respond doesn't it?

**Comment by grdddj** [comment]
Yes, it is very unexpected, no idea why (also it could be just my local issue).

Also, when the `bridge` is running, there are some HTTP logs being printed into the console, even if it is being spawned in a separate process (and they are not connected to the background check we do from `index`).

Maybe my understanding of `bridge` is not complete - what is it "really" doing?

**Comment by tsusanka** [comment]
Bridge is just a simple HTTP server on one side which receives requests and sends these via USB to the device. Repo: github.com/trezor/trezord-go/

**Comment by tsusanka** [comment]
I mean this code removes code which is always nice :) so I am merging. If you would have some time in future feel free to investigate.

**Pull request merged**
