### PR TITLE
Dashboard style improvements

### PR DESCRIPTION
**Pull request by enjojoy**
On a larger screen it will divide into 2 columns for convenience. Also I added Trezor font and slightly adjusted layout of the buttons.

image
image

### CODE REVIEW

**Comment by enjojoy** [comment]
@grdddj Could you please review

**Review by vdovhanych — APPROVED** [review]
Thanks for the addition. I think the UI update is neat, and I have nothing against it. Also, this dashboard needs a lot more love in general 😄.

**Comment by enjojoy** [comment]
> Thanks for the addition. I think the UI update is neat, and I have nothing against it. Also, this dashboard needs a lot more love in general 😄. 

Thank you.😊 I agree, in the future I can see how it can be improved further.

**Comment by enjojoy** [comment]
Let's not merge yet, I will add Trezor theme styles to buttons and inputs

**Comment by enjojoy** [comment]
Improved buttons and input an select components, now I think it's ready to merge

image
image

**Comment by enjojoy** [comment]
@grdddj  Please review :)

**Comment by grdddj** [comment]
LGTM, thanks for the changes!

**Pull request merged**
