### PR TITLE
Support model R emulators

### PR DESCRIPTION
**Pull request by grdddj**
Connected with https://github.com/trezor/trezor-user-env/issues/176:
- supporting model R in `tenv`

Is a little hacky, for couple of reasons/limitations:
- we need the latest `trezorlib` for `model R` support, but it is unreleased
  - I am unable to install it from our github repo through `poetry install` ([known issue](https://github.com/python-poetry/poetry/issues/755)), so I am doing it manually through `pip` in `Dockerfile` as a last step
- we need functional `model R` emulator(s), but they are not yet released
  - in current `master` we do have it running, just with a very limited capabilities
  - therefore, I am hardcoding download of from the "most featured branch" currently ([grdddj/trezor_r_passphrase_input](https://github.com/trezor/trezor-firmware/tree/grdddj/trezor_r_passphrase_input)), which has prototypes of PIN entry, seed backup, seed recovery and passphrase entry

It is however easily possible for anybody to download any branch through the `Start from URL` feature - just giving it URL to some Gitlab job of `core unix frozen R debug build` (for example https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/2498092302) and choosing `TR`.

What is currently missing is support for `ARM` - sorry guys @vdovhanych @sime @tsusanka - but it could be possible to add some `model R ARM build` info `firmware CI` :)

### CODE REVIEW

**Comment by grdddj** [comment]
> I will try to build a model R emulator on arm, if that works then there should be no reason it shouldn't work on m1. I will let you know here.

Thanks. I think the `arm` version should be fine already - `firmware CI` built it - https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/2510249260 - and @sime verified it can be run through `tenv`

**Comment by tsusanka** [comment]
@grdddj is this ready to be reviewed and merged? Btw matejcik made a hotfix after the first trezorctl release (0.13.2), does this include that instead of the first version?

**Comment by tsusanka** [comment]
Ok just ping me if this would wait for me please :).

**Comment by grdddj** [comment]
> Ok just ping me if this would wait for me please :).

@tsusanka pinging you, as I think it is now ready for review and merge :)

The PR contains even some "non-modelR" things - see the list of commits

**Review by tsusanka — APPROVED** [review]
We could bikeshed some things but I do not think it is needed :). LGTM.

I will merge this on Wednesday due to the holidays. cc @mroz22 just so you know if you notice something odd on Suite side after the merge.

**Pull request merged**
