### PR TITLE
Grdddj/docker more cache reuse

### PR DESCRIPTION
**Pull request by grdddj**
Experiment `PR` trying to address https://github.com/trezor/trezor-user-env/issues/153

### CODE REVIEW

**Comment by vdovhanych** [comment]
Just FYI we will no longer be using GitLab for building the image I feel this is just lost time as we do not control the GitHub runner and thus caching is not really something we would see any improvements to it.

**Comment by grdddj** [comment]
> Just FYI we will no longer be using GitLab for building the image I feel this is just lost time as we do not control the GitHub runner and thus caching is not really something we would see any improvements to it.

I feel the same, it is probably not worth spending time with. We will have to live with building, pushing, storing and pulling every single image/layer separately without reuse (apart from the base image).

**Comment by tsusanka** [comment]
Yeah this seems too wild 😢. So closing? Thanks @grdddj though!

**Comment by grdddj** [comment]
> Yeah this seems too wild cry. So closing? Thanks @grdddj though!

Sure, we can close it as an experiment, together with the issue probably :) 

One thing from this theoretically could be used, and that is the inclusion of `.git` directory in `.dockerignore`, as it has `88 MB` currently and will be only growing. We could save that space in every image.

(one thing that the omission of `.git` directory does is `fatal: not a git repository (or any of the parent directories): .git` error at the end of `nix-shell` installation - can be seen at https://gitlab.com/satoshilabs/trezor/trezor-user-env/-/jobs/2263134247 at line `751` - but it does not seem influencing anything)

**Comment by tsusanka** [comment]
Seems nice to have to omit the .git directory. How big is the image btw? Is 88 significant part?

**Comment by tsusanka** [comment]
It is so big I would not worry about it.. For now..

**Pull request closed without merging**
