### PR TITLE
chore(ci): update to the latest stable nix and official nix image

### PR DESCRIPTION
**Pull request by vdovhanych**
Updates nixos to upstream docker image.

### CODE REVIEW

**Comment by vdovhanych** [comment]
so it looks like we're finally able to use the official nix image again. @grdddj do you remember what jobs were failing after the nix image was updated? I think it was something related to connect in the firmware repo.

**Comment by grdddj** [comment]
> so it looks like we're finally able to use the official nix image again. @grdddj do you remember what jobs were failing after the nix image was updated? I think it was something related to connect in the firmware repo.

Not remember anymore. `tenv` is not used at so many places, so `Connect` tests in `firmware` is a probable option

**Comment by vdovhanych** [comment]
What about just shipping it and seeing if it breaks anything? I know it's kind of yolo, but I tested the image locally, and everything seems to be working fine. @tsusanka @grdddj

**Comment by grdddj** [comment]
Agreed, let's try and see. Revert in the worst case :D

**Pull request merged**
