### PR TITLE
chore(binaries): change latest emulators name from master to main

### PR DESCRIPTION
**Pull request by grdddj**
Naming changes from `master` to `main`

### CODE REVIEW

**Comment by vdovhanych** [comment]
We should inform the suite team before so they can change their test to reflect the change to main.

**Review by vdovhanych — APPROVED** [review]

**Comment by grdddj** [comment]
> We should inform the suite team before so they can change their test to reflect the change to main.

Thanks for the reminder, I wrote them on Slack

**Comment by vdovhanych** [comment]
We can merge this, as they are informed about the change and they need the new images to be able to change this, it will fail either way until both is fixed :)

**Comment by grdddj** [comment]
> We can merge this, as they are informed about the change and they need the new images to be able to change this, it will fail either way until both is fixed :)

Right, I have pushed a backwards-compatible fix, so we can definitely merge it now and it will not break anything for `Suite`. 

Seems with the new commit Merging got blocked - will you please approve again?

**Review by vdovhanych — APPROVED** [review]
lgtm

**Pull request merged**
