### PR TITLE
feat(docker): showing version details when running docker container

### PR DESCRIPTION
**Pull request by grdddj**
Trying to address issue #65
- when running a docker container, it shows multiple git details - the branch, commit amount (aka version) and the details of last commit

### CODE REVIEW

**Comment by grdddj** [comment]
It is probably off-topic in this PR, but when trying to run the docker container (built locally to test this version functionality), I received an error in `run.sh`, in `nix-shell --run "trezorctl --version"` command - could not find version.

Has it ever been encountered?

NOTE: For my purposes, I have disabled all the `download.sh` lines in Dockerfile, to have it built faster - theoretically that may be the culprit, but these should have nothing to do with `trezorlib`, it is defined only in `shell.nix`

image

**Comment by grdddj** [comment]
UPDATE on error above:
- the whole trezorlib is working fine apart from this `--version` command
- even locally the same command - `nix-shell --run "trezorctl --version"` throws the same error
- (this `--version` is a default `click` functionality)
- when running "our" command for version in trezorlib - `nix-shell --run "trezorctl version"` (without the "--"), it is working fine (comparison below)

I know that I am hijacking this PR, but since I already made one comment about it here, am following with this here as well. Is it worth creating a separate issue for this?

image

**Comment by tsusanka** [comment]
Aaah and have we ever even supported `trezorctl --version`? :thinking: Maybe it was just `trezorctl version` all the time and it was incorrect all the time here in trezor-user-env. Could you please create an issue in trezor-firmware? Matejcik will advise there and it is indeed off-topic here.

**Comment by tsusanka** [comment]
And in the meantime please remove the `--` here in this PR.

**Review by tsusanka — COMMENTED** [review]
This is great :clap: :clap:. Please:
- Let's move `create_version_file.sh` into the `docker`
- Same for the `version.txt` although that does not matter that much
- Add `docker/version.txt` to `.gitignore` so we do not create a possible conflict in future
- Remove the `--` in `trezortl --version`
- Rebase on top of the new `incoming`

Feel free to force-push directly, this is a tiny PR so we'll manage :).

**Comment by grdddj** [comment]
> Aaah and have we ever even supported `trezorctl --version`?

Yes, under "normal" circumstances, this command seems to work out of the box from the `click` library used for creating the trezorctl CLI.

Even when I simply get out of the nix-shell and run it with my laptop NixOS, it is fine:
image

Therefore it is probable that there is some incompatibility of `click` library installed by the new shell.nix here (through the `trezor` package)

**Comment by grdddj** [comment]
@tsusanka Meanwhile I am creating the issue in firmware repo, can you please try to run this command as well on your machine (in root folder in this branch), so we know it is not connected only to my PC?

`nix-shell --run "trezorctl --version"`

(I tried to run it on `master` branch (as `nix-shell controller/shell.nix  --run "trezorctl --version"`), and it is fine there - there is older shell.nix file)

**Comment by tsusanka** [comment]
Yes I am getting the same error on 0abb0ffbcdb62b3038e3d446eca27c5b805843b1.

**Comment by grdddj** [comment]
> Yes I am getting the same error on [0abb0ff](https://github.com/trezor/trezor-user-env/commit/0abb0ffbcdb62b3038e3d446eca27c5b805843b1).

Thanks for verifying, on `incoming` it is the same, so with a high probability it is caused by the NixOS update we did.

As mentioned in the [firmware issue](https://github.com/trezor/trezor-firmware/issues/1702), it is not a blocker for us - as we run this command only for informational purposes, and the error does not cause any issue with our main script. However it may be an issue for someone else.

**Comment by grdddj** [comment]
Commit 2cc65c4:
- incorporating the comments above
  - moving the version-file-generating script
  -  changing the _version_ command for trezorctl and reflecting the new output (does not show the _trezorctl_ in any way, is just a version number now - therefore prepending it with a description text)

**Review by tsusanka — APPROVED** [review]

**Comment by tsusanka** [comment]
Great! You are moving so fast I'll have to start about new issues :)).

**Pull request merged**
