### PR TITLE
Revert "fix(nix): correct autoPatchelf behavior"

### PR DESCRIPTION
**Pull request by vdovhanych**
This reverts commit 7740e3b.- Revert "fix(nix): correct autoPatchelf behavior"
- Revert "chore(ci): unite nix versions with firmware"
- chore: update trezorctl to latest version

After we merged these changes the tenv server wouldn't start up at all in docker. I have tested it and it was working for a bit but now its not even starting after the latest rebuild. Also updating trezorctl version to latest.

### CODE REVIEW

**Comment by vdovhanych** [comment]
Lets wait for testing image

**Comment by vdovhanych** [comment]
I guess it's because it is used as the base docker image in there.

**Comment by grdddj** [comment]
Artifacts from https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/2666971555 however show that the `tenv` was started - so the issue might be just `Suite` tests connecting to it.

It might have problems resolving the websocket endpoint maybe. That is the issue we had in `firmware` and that was solved by https://github.com/trezor/trezor-firmware/pull/2357 - in short, `CI` servers could not resolve `localhost`, so we had to change it to `127.0.0.1`. If `Suite` and `firmware` use the same `Gitlab` servers, that might easily be the case

**Comment by vdovhanych** [comment]
closing this as we fixed it with docker update

**Pull request closed without merging**
